/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthErrorRouteImport } from './routes/auth-error'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTokensRouteImport } from './routes/_authenticated/tokens'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedImagesRouteImport } from './routes/_authenticated/images'
import { Route as FormsPublicPublicIdRouteImport } from './routes/forms/public/$publicId'
import { Route as FormsPreviewIdRouteImport } from './routes/forms/preview/$id'
import { Route as FormsInvitesTokenRouteImport } from './routes/forms/invites/$token'
import { Route as AuthenticatedFormsIdResponsesRouteImport } from './routes/_authenticated/forms/$id/responses'
import { Route as AuthenticatedFormsIdEditRouteImport } from './routes/_authenticated/forms/$id/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth-error',
  path: '/auth-error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTokensRoute = AuthenticatedTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImagesRoute = AuthenticatedImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const FormsPublicPublicIdRoute = FormsPublicPublicIdRouteImport.update({
  id: '/forms/public/$publicId',
  path: '/forms/public/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsPreviewIdRoute = FormsPreviewIdRouteImport.update({
  id: '/forms/preview/$id',
  path: '/forms/preview/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsInvitesTokenRoute = FormsInvitesTokenRouteImport.update({
  id: '/forms/invites/$token',
  path: '/forms/invites/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFormsIdResponsesRoute =
  AuthenticatedFormsIdResponsesRouteImport.update({
    id: '/forms/$id/responses',
    path: '/forms/$id/responses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormsIdEditRoute =
  AuthenticatedFormsIdEditRouteImport.update({
    id: '/forms/$id/edit',
    path: '/forms/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth-error': typeof AuthErrorRoute
  '/login': typeof LoginRoute
  '/images': typeof AuthenticatedImagesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tokens': typeof AuthenticatedTokensRoute
  '/forms/invites/$token': typeof FormsInvitesTokenRoute
  '/forms/preview/$id': typeof FormsPreviewIdRoute
  '/forms/public/$publicId': typeof FormsPublicPublicIdRoute
  '/forms/$id/edit': typeof AuthenticatedFormsIdEditRoute
  '/forms/$id/responses': typeof AuthenticatedFormsIdResponsesRoute
}
export interface FileRoutesByTo {
  '/auth-error': typeof AuthErrorRoute
  '/login': typeof LoginRoute
  '/images': typeof AuthenticatedImagesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tokens': typeof AuthenticatedTokensRoute
  '/': typeof AuthenticatedIndexRoute
  '/forms/invites/$token': typeof FormsInvitesTokenRoute
  '/forms/preview/$id': typeof FormsPreviewIdRoute
  '/forms/public/$publicId': typeof FormsPublicPublicIdRoute
  '/forms/$id/edit': typeof AuthenticatedFormsIdEditRoute
  '/forms/$id/responses': typeof AuthenticatedFormsIdResponsesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth-error': typeof AuthErrorRoute
  '/login': typeof LoginRoute
  '/_authenticated/images': typeof AuthenticatedImagesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tokens': typeof AuthenticatedTokensRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/forms/invites/$token': typeof FormsInvitesTokenRoute
  '/forms/preview/$id': typeof FormsPreviewIdRoute
  '/forms/public/$publicId': typeof FormsPublicPublicIdRoute
  '/_authenticated/forms/$id/edit': typeof AuthenticatedFormsIdEditRoute
  '/_authenticated/forms/$id/responses': typeof AuthenticatedFormsIdResponsesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth-error'
    | '/login'
    | '/images'
    | '/settings'
    | '/tokens'
    | '/forms/invites/$token'
    | '/forms/preview/$id'
    | '/forms/public/$publicId'
    | '/forms/$id/edit'
    | '/forms/$id/responses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth-error'
    | '/login'
    | '/images'
    | '/settings'
    | '/tokens'
    | '/'
    | '/forms/invites/$token'
    | '/forms/preview/$id'
    | '/forms/public/$publicId'
    | '/forms/$id/edit'
    | '/forms/$id/responses'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth-error'
    | '/login'
    | '/_authenticated/images'
    | '/_authenticated/settings'
    | '/_authenticated/tokens'
    | '/_authenticated/'
    | '/forms/invites/$token'
    | '/forms/preview/$id'
    | '/forms/public/$publicId'
    | '/_authenticated/forms/$id/edit'
    | '/_authenticated/forms/$id/responses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthErrorRoute: typeof AuthErrorRoute
  LoginRoute: typeof LoginRoute
  FormsInvitesTokenRoute: typeof FormsInvitesTokenRoute
  FormsPreviewIdRoute: typeof FormsPreviewIdRoute
  FormsPublicPublicIdRoute: typeof FormsPublicPublicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-error': {
      id: '/auth-error'
      path: '/auth-error'
      fullPath: '/auth-error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tokens': {
      id: '/_authenticated/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof AuthenticatedTokensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/images': {
      id: '/_authenticated/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof AuthenticatedImagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/forms/public/$publicId': {
      id: '/forms/public/$publicId'
      path: '/forms/public/$publicId'
      fullPath: '/forms/public/$publicId'
      preLoaderRoute: typeof FormsPublicPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/preview/$id': {
      id: '/forms/preview/$id'
      path: '/forms/preview/$id'
      fullPath: '/forms/preview/$id'
      preLoaderRoute: typeof FormsPreviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/invites/$token': {
      id: '/forms/invites/$token'
      path: '/forms/invites/$token'
      fullPath: '/forms/invites/$token'
      preLoaderRoute: typeof FormsInvitesTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/forms/$id/responses': {
      id: '/_authenticated/forms/$id/responses'
      path: '/forms/$id/responses'
      fullPath: '/forms/$id/responses'
      preLoaderRoute: typeof AuthenticatedFormsIdResponsesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forms/$id/edit': {
      id: '/_authenticated/forms/$id/edit'
      path: '/forms/$id/edit'
      fullPath: '/forms/$id/edit'
      preLoaderRoute: typeof AuthenticatedFormsIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedImagesRoute: typeof AuthenticatedImagesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTokensRoute: typeof AuthenticatedTokensRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedFormsIdEditRoute: typeof AuthenticatedFormsIdEditRoute
  AuthenticatedFormsIdResponsesRoute: typeof AuthenticatedFormsIdResponsesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedImagesRoute: AuthenticatedImagesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTokensRoute: AuthenticatedTokensRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedFormsIdEditRoute: AuthenticatedFormsIdEditRoute,
  AuthenticatedFormsIdResponsesRoute: AuthenticatedFormsIdResponsesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthErrorRoute: AuthErrorRoute,
  LoginRoute: LoginRoute,
  FormsInvitesTokenRoute: FormsInvitesTokenRoute,
  FormsPreviewIdRoute: FormsPreviewIdRoute,
  FormsPublicPublicIdRoute: FormsPublicPublicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
