/**
 * アプリケーション全体で使用するエラーコードの定数
 */
export const ERROR_CODES = {
  // フォーム関連エラー
  FORM_NOT_FOUND: "FORM_NOT_FOUND",
  INVALID_STRUCTURE: "INVALID_STRUCTURE",
  INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",
  FORM_ALREADY_EXISTS: "FORM_ALREADY_EXISTS",

  // バリデーションエラー
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_DATE_FORMAT: "INVALID_DATE_FORMAT",
  INVALID_DATE_RANGE: "INVALID_DATE_RANGE",
  INVALID_REQUEST: "INVALID_REQUEST",

  // データベースエラー
  DATABASE_ERROR: "DATABASE_ERROR",
  CONSTRAINT_VIOLATION: "CONSTRAINT_VIOLATION",
  TRANSACTION_FAILED: "TRANSACTION_FAILED",

  // 認証・認可エラー
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  INVALID_TOKEN: "INVALID_TOKEN",
  INSUFFICIENT_SCOPE: "INSUFFICIENT_SCOPE",
  FORM_ACCESS_DENIED: "FORM_ACCESS_DENIED",
  AUTH_FAILED: "AUTH_FAILED",
  INVALID_JSON: "INVALID_JSON",

  // システムエラー
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  INTERNAL_ERROR: "INTERNAL_ERROR",

  // API操作エラー
  CREATE_FORM_ERROR: "CREATE_FORM_ERROR",
  UPDATE_FORM_ERROR: "UPDATE_FORM_ERROR",
  DELETE_FORM_ERROR: "DELETE_FORM_ERROR",
  PUBLISH_FORM_ERROR: "PUBLISH_FORM_ERROR",
  UNPUBLISH_FORM_ERROR: "UNPUBLISH_FORM_ERROR",
  GET_FORMS_ERROR: "GET_FORMS_ERROR",
  GET_FORM_ERROR: "GET_FORM_ERROR",
  INTEGRATION_NOT_FOUND: "INTEGRATION_NOT_FOUND",
  GET_INTEGRATION_ERROR: "GET_INTEGRATION_ERROR",
  UPSERT_INTEGRATION_ERROR: "UPSERT_INTEGRATION_ERROR",
  DELETE_INTEGRATION_ERROR: "DELETE_INTEGRATION_ERROR",

  // バージョン管理関連エラー
  VERSION_NOT_FOUND: "VERSION_NOT_FOUND",
  TARGET_VERSION_NOT_FOUND: "TARGET_VERSION_NOT_FOUND",
  SOURCE_VERSION_NOT_FOUND: "SOURCE_VERSION_NOT_FOUND",
  ONE_OR_BOTH_VERSIONS_NOT_FOUND: "ONE_OR_BOTH_VERSIONS_NOT_FOUND",
  VERSION_NUMBER_CONFLICT: "VERSION_NUMBER_CONFLICT",
  NO_VERSIONS_FOUND: "NO_VERSIONS_FOUND",
  VERSION_ALREADY_PUBLISHED: "VERSION_ALREADY_PUBLISHED",

  // バージョン操作エラー
  CREATE_VERSION_ERROR: "CREATE_VERSION_ERROR",
  GET_VERSION_ERROR: "GET_VERSION_ERROR",
  GET_VERSIONS_ERROR: "GET_VERSIONS_ERROR",
  ROLLBACK_VERSION_ERROR: "ROLLBACK_VERSION_ERROR",
  PUBLISH_VERSION_ERROR: "PUBLISH_VERSION_ERROR",
  VERSION_DIFF_ERROR: "VERSION_DIFF_ERROR",

  // スケジュール処理エラー
  SCHEDULE_PROCESSING_ERROR: "SCHEDULE_PROCESSING_ERROR",
  SCHEDULE_NOT_FOUND: "SCHEDULE_NOT_FOUND",
  SCHEDULE_PROCESSED: "SCHEDULE_PROCESSED",
  CREATE_SCHEDULE_ERROR: "CREATE_SCHEDULE_ERROR",
  UPDATE_SCHEDULE_ERROR: "UPDATE_SCHEDULE_ERROR",
  DELETE_SCHEDULE_ERROR: "DELETE_SCHEDULE_ERROR",
  GET_SCHEDULE_ERROR: "GET_SCHEDULE_ERROR",
  GET_SCHEDULES_ERROR: "GET_SCHEDULES_ERROR",

  // 共有リンク関連エラー
  SHARE_LINK_NOT_FOUND: "SHARE_LINK_NOT_FOUND",
  SHARE_LINK_EXPIRED: "SHARE_LINK_EXPIRED",
  SHARE_LINK_ACCESS_ERROR: "SHARE_LINK_ACCESS_ERROR",
  CREATE_SHARE_LINK_ERROR: "CREATE_SHARE_LINK_ERROR",
  UPDATE_SHARE_LINK_ERROR: "UPDATE_SHARE_LINK_ERROR",
  DELETE_SHARE_LINK_ERROR: "DELETE_SHARE_LINK_ERROR",
  GET_SHARE_LINKS_ERROR: "GET_SHARE_LINKS_ERROR",
} as const;

/**
 * エラーコードの型
 */
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/**
 * エラーレスポンスの標準形式
 */
export interface StandardErrorResponse {
  error: {
    code: ErrorCode;
    message: string;
    details?: Record<string, unknown>;
  };
  timestamp: string;
  path?: string;
}
