export enum DiscordErrorCode {
  DISCORD_API_RATE_LIMIT = "DISCORD_API_RATE_LIMIT",
  DISCORD_GUILD_NOT_FOUND = "DISCORD_GUILD_NOT_FOUND",
  DISCORD_USER_NOT_MEMBER = "DISCORD_USER_NOT_MEMBER",
  DISCORD_ROLE_REQUIREMENT_UNMET = "DISCORD_ROLE_REQUIREMENT_UNMET",
  DISCORD_BOT_NOT_IN_GUILD = "DISCORD_BOT_NOT_IN_GUILD",
  DISCORD_API_ERROR = "DISCORD_API_ERROR",
}
