export enum GitHubErrorCode {
  GITHUB_API_RATE_LIMIT = "GITHUB_API_RATE_LIMIT",
  GITHUB_USER_NOT_FOUND = "GITHUB_USER_NOT_FOUND",
  GITHUB_AUTH_FAILED = "GITHUB_AUTH_FAILED",
  GITHUB_API_ERROR = "GITHUB_API_ERROR",
  NETWORK_ERROR = "NETWORK_ERROR",
  TIMEOUT = "TIMEOUT",
}
